-- Insert sample restaurants
INSERT INTO restaurants (name, opening_time, closing_time, created_at, updated_at) VALUES
('The Green Garden', '08:00:00', '22:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Steakhouse Prime', '11:00:00', '23:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vegan Paradise', '07:00:00', '21:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Italian Bistro', '12:00:00', '23:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seafood Fresh', '11:30:00', '22:30:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert restaurant endorsements
INSERT INTO restaurant_endorsements (restaurant_id, endorsement_type) VALUES
(1, 'VEGETARIAN'), (1, 'VEGAN'), (1, 'GLUTEN_FREE'),
(2, 'PALEO'), (2, 'KETO'),
(3, 'VEGAN'), (3, 'VEGETARIAN'), (3, 'RAW_FOOD'),
(4, 'VEGETARIAN'), (4, 'GLUTEN_FREE'),
(5, 'NUT_FREE'), (5, 'DAIRY_FREE');

-- Insert restaurant tables
INSERT INTO restaurant_tables (restaurant_id, capacity, created_at, updated_at) VALUES
(1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
